### ISSUE TITLE
Questão com grafia incorreta

### ISSUE THREAD

**Issue by aphenrique** [tlcdio/CLBSAula01#1]
Olá professor.

Ao responder o questionário final do curso, me deparei com duas questões com grafia incorreta, estou postando aqui para que possa corrigir, se for o caso.

![Questão incorreta Operadores](https://user-images.githubusercontent.com/11799547/141693820-8440fe7b-9ccb-4332-add0-700841b2d367.png)

No caso, o operador ">;" também está incorreto por causa do "ponto e vírgula".

ps.: Eu mencionei duas questões com grafia incorreta, mas o print foi sobrescrito por esta segunda, mas creio que não haverá dificuldade em encontrá-la.

Abraço

**Comment by tlcdio** [comment]
Olá Henrique. Obrigado. Repassarei ao pessoal da DIO.
Desculpe pela demora em te responder.

Tudo de bom.

**Comment by tlcdio** [comment]
E outro detalhe, foi erro de digitação mesmo. Minha intenção não era ter
esse ";". kkkkk

**Comment by aphenrique** [comment]
👍🏽
